### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by bennypowers** [RedHat-UX/red-hat-icons#3]
## TODO:
- [x] build scripts that generate optimized svg, jpg, png, webp, and eps artifacts, including red and white variants
- [x] ci/cd which adds artifacts to github releases
- [x] documentation, readme, contributing.md, etc
- [x] ~~automation to detect name conflicts (git hooks?)~~: Not doing this right now, can revisit later if deemed an issue
- [x] linting/verifying monotone icons work properly (no `fill` or `fill="currentColor"`)

**Comment by zeroedin** [comment]
> - [ ] build scripts that generate optimized svg, jpg, png, webp, and eps artifacts, including red and white variants

Is this still valid?  Or are we sticking with svg only and svgo optomization?

> - [ ] ci/cd which adds artifacts to github releases

Assuming artifacts are just similar to pf-icons here  (@bennypowers in chat: "I'd like to export nodes from modules in the icons repo, like we do in PFE icons")

> - [ ] documentation, readme, contributing.md, etc

How much of this do we need to do here vs on ux?  Should I reach to to Ryan about how someone may contribute back how he wants that process to go for creating and adding a new icon here?

> - [ ] automation to detect name conflicts (git hooks?)

What all does that entail?  Are we worried about someone adding the same icon name in multiple set folders?

> - [ ] linting/verifying monotone icons work properly (no `fill` or `fill="currentColor"`)

 This still valid?  Given svg's with no fill setting in CSS should be enough.

**Comment by bennypowers** [comment]
- We should run a build step which adds javascript modules to the npm tarball
- the artifacts should probably just be the npm tarball
- we need at least a README.md and CONTRIBUTING.md, and maybe some issue templates
- if you're not worried about name conflicts we can sleep on it
- duotone is no longer an issue, but then we should verify that all the icons have no fill

**Comment by zeroedin** [comment]
> the artifacts should probably just be the npm tarball

Do we want both the js modules AND the svg files as in pfe in the `dist/`?

**Comment by bennypowers** [comment]
Yes I think so
